### ISSUE TITLE
Example output

### ISSUE THREAD

**Issue by arcotek-ltd** [Azure/azure-docs-json-samples#40]
@tfitzmac, could you add expected output examples for [crossresourcegroupproperties.json](https://github.com/Azure/azure-docs-json-samples/blob/master/azure-resource-manager/crossresourcegroupproperties.json) please?

Either here or [here](https://docs.microsoft.com/en-us/azure/azure-resource-manager/resource-manager-cross-resource-group-deployment#example-templates).

Thanks

**Comment by arcotek-ltd** [comment]
So the first two return parentGroup, whereas the last one returns the linkedGroup. Is this correct?

How do you return inlineGroup?

`resources.resourceGroup = inlineGroup` doesn't do anything.

Thanks

**Comment by tfitzmac** [comment]
@arcotek-ltd - thanks for this suggestion. I have added the expected output to the article. It will either get published this afternoon or Monday AM.

You are right the first two output values return parentGroup, and the last returns linkedGroup.

The only ways to return inlineGroup would be to either move the nested template to a linked template, or add a linked template that just returns that resource group. For example, if you added:

{
            "apiVersion": "2017-05-10",
            "name": "secondTemplate",
            "type": "Microsoft.Resources/deployments",
            "resourceGroup": "inlineGroup",
            "dependsOn": [
                "nestedTemplate"
            ],
            "properties": {
                "mode": "Incremental",
                "templateLink": {
                    "contentVersion": "1.0.0.0",
                    "uri": "https://raw.githubusercontent.com/Azure/azure-docs-json-samples/master/azure-resource-manager/functions/resourcegroup.json"
                },
                "parameters": {}
            }
        }

You could get the resource group in the outputs with:

"inlineRG2": {
            "type": "object",
            "value": "[reference('secondTemplate').outputs.resourceGroupOutput.value]"
        }
