### ISSUE TITLE
Unable to use functions in parameters for default value.

### ISSUE THREAD

**Issue by vivekkumac** [Azure/azure-docs-json-samples#42]
As per https://github.com/Azure/azure-docs-json-samples/blob/master/azure-resource-manager/parameterswithfunctions.json, I tried using functions to set default value to parameters which is failing for me.
On setting a parameter as
...`
"virtualMachineName": {
            "defaultValue": "[concat('vm', uniqueString(resourceGroup().id))]",
            "type": "string"
        },
...
`
default value is not as expected:

![image](https://user-images.githubusercontent.com/4416995/37949861-ff0d60b4-31b3-11e8-8e6a-cbb155e919d7.png)

**Comment by tfitzmac** [comment]
@vivekkumac - it looks like you are using a UI for deployment. Is it the portal? It is possible that functions in the default value will not work with the portal. It works with PowerShell or CLI.
